### ISSUE TITLE
オフィスアワー的なものの提案

### ISSUE THREAD

**Issue by androhi** [DroidKaigi/droidkaigi#14]
提案です。

懇親会という形もいいのですが、もうちょっと目的をはっきりさせて、登壇者とコミュケーションを取れる時間として設けるのもいいのかなと思いました。（Googleのイベントだと、よくオフィスアワーって呼んでる気がします。）

イメージとしては、セッションと平行して別室の小部屋みたいな場所で、時間きめてセッション中以外の登壇者と情報交換できる感じです。セッションによっては興味ある人とない人で別れると思うので、そういう場合に興味ある分野の登壇者とコミュニケーションとれると、有意義に過ごせるかなと。

もちろん会場的にそのような場所が確保できることが大前提にはなりますが…。

**Comment by wasabeef** [comment]
小部屋みたいな場所を確保するのは難しいのと
廊下になると他社さんの迷惑になってしまうので
セミナールームで隅っこで小さくパーティション区切れればと思ってるんですが
そんなに区切る備品が無いと思います、現地の写真撮影するときに合わせて確認します

**Comment by androhi** [comment]
なるほど、ありがとうございます！
難しそうなら無理せず、次回やれたらいいねくらいでもいいかもしれないですね。
