### ISSUE TITLE
Google Spreadsheetsでは、非表示セルもダウンロードしたら表示できてしまう

### ISSUE THREAD

**Issue by mhidaka** [DroidKaigi/droidkaigi#55]
見せたくない情報があったとき、スプレットシートの表示／非表示を切り替えるだけでは不十分

https://productforums.google.com/forum/#!topic/docs/AgZMYl0oOcE

にも同様の指摘あり。

解決のためにはスクリプトなどで別のスプレットシートに転記しなければならない。

**Comment by roishi2j2** [comment]
スクリプトはいりません。

=importrange("(自主規制)", "セル番号")

で必要なセルだけ引っ張って来れます。
オレオレシートからimportrangeできないように適切に権限を設定する必要はあります。
